<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../BossMod/BossModReborn.csproj" />
    <Reference Include="Lumina" HintPath="$(appdata)/XIVLauncher/addon/Hooks/dev/Lumina.dll" Private="false" />
    <Reference Include="Lumina.Excel" HintPath="$(appdata)/XIVLauncher/addon/Hooks/dev/Lumina.Excel.dll" Private="false" />
  </ItemGroup>
</Project>
